### ISSUE TITLE
Final Request for grade - Cozy website

### ISSUE THREAD

**Issue by JiffyBees** [JiffyBees/ecommerce-pattern-library#15]
Rationale
My Website cozy was made to reflect large e-commerce stores with many products and possible retail stores. Indigo and Bath & body works were inspirations to the final design, helping to create a believable e-commerce layout. I feel that action cards were a little overused in my design, limiting the design potential an e-commerce website really has. Structurally however my website reflects the hundreds of pages a real online store would have. I am proud of the code used for this website, making a consistent well-performing platform that can have content easily inserted. Though we did not send our code to other group members I feel like my website has been structured well enough for web designers to understand.

---

*Style & design* — **3**

aesthetically I feel like my website could be better but as an e-commerce website, It works well to portray the real amount of pages that would exist, while functioning at all sizes.

*Patterns* — **3**

I made the standard patterns for header, nav, etc.. but I also made extra style options for buttons and cards that would help with the other possible pages. If given more time I would have made Illustrations and more graphics for the branding, along with more seasonal ad cards but what I made now is very inclusive.

*Explanations* — **2**

Explanations in the pattern library were very brief but to the point, items used multiple times are detailed, however. This limited explanation makes it easier to understand their usability but can be difficult for newcomers to the project.

*Accessibility* — **2.5**

Voice over was tested as well as some amount of colour blindness, however, I do not feel like my website 100% accommodates people with other disabilities.

*Semantics* — **2**

The standard tags were used in my code alongside some more complex tags. I used what I felt was most appropriate even if there may have been better items. I know for example sections, and mains were not often used because divs worked well and structure in an e-commerce website is very prone to change.

*Responsiveness* — **2.5**

Almost all elements work on all pages, there are a couple of buttons and cards that are a little bit squished in between sizes.

*Code quality* — **2.5**

Decent: most minor issues are from possible spacing and indentation issues that were missed.

*Git & commits* — **2.5**

All git commits were made in full short sentences with title case standard and informative starting words like Fix, Add, or Removed

---

20/24 — **83%**
@thomasjbradley

I hope you have a very good day - Vanessa R

**Comment by thomasjbradley** [comment]
I’m really happy with what you produced: it’s one of only a few websites that truly look like a large-scale ecommerce website. Thanks for putting in the effort & applying this term’s materials.
