### ISSUE TITLE
Placeholder items homepage

### ISSUE THREAD

**Issue by JiffyBees** [JiffyBees/ecommerce-pattern-library#3]
@thomasjbradley
My homepage is almost done, I just have an issue with putting images into my placeholders and reducing the number of displayed product cards down to one line, I'm not sure how to do this.

**Comment by thomasjbradley** [comment]
You can limit how many products are shown using `limit:4`, on this line:
https://github.com/JiffyBees/ecommerce-pattern-library/blob/master/index.html#L21

```html
{% for product in site.products limit:4 %}
```

**Comment by thomasjbradley** [comment]
For the images, let’s look at the `tab-card-image.html` pattern as an example.

In the pattern, change the `<img src="">` to a placeholder:
https://github.com/JiffyBees/ecommerce-pattern-library/blob/master/_patterns/cards/tab-card-image.html#L3

```html
<img class="img-flex" src="{{include.image}}"
```

Then, on the homepage, when using the pattern, you need to specify the `image` placeholder as an attribute:
https://github.com/JiffyBees/ecommerce-pattern-library/blob/master/index.html#L38

```html
{% pattern cards/tab-card-image image="/images/blah-whatever.jpg" %}
```

**Comment by JiffyBees** [comment]
@thomasjbradley 
Is there a way to limit the number of products at certain sizes. Like 2 products at the lowest size but 4 at the largest?
