### ISSUE TITLE
Completed surprise ecommerce pages

### ISSUE THREAD

**Issue by JiffyBees** [JiffyBees/ecommerce-pattern-library#7]

**Comment by JiffyBees** [comment]
Hopefully, I haven't missed anything. let me know if you see any issues.
@thomasjbradley

**Comment by thomasjbradley** [comment]
Rename them to something appropriate for an ecommerce website, like `privacy-terms.html` & `deals.html` or something.

**Comment by JiffyBees** [comment]
Ok, I've renamed them.
@thomasjbradley
